### ISSUE TITLE
Cannot select multiple playlist entries because of single click play action

### ISSUE THREAD

**Issue by sleeksorrow** [smplayer-dev/smplayer#182] opened 2021-08-29 05:23 UTC
**Describe the bug**
I cannot select multiple playlist entries either by clicking the first entry, then shift-click the last one to select all in between. Or select multiple entries by ctrl-clicking them. Because with the first click the entry starts to play and all other selections are cleared.

**To Reproduce**
1. add multiple videos to the playlist
2. click the first one (it starts to play immediately)
3. shift-click a video further down the play list (it starts to play immediately)
4. see that the first entry is deselected

**Expected behavior**
1. add multiple videos to the playlist
2. click the first one
3. shift-click a video further down the play list
4. See that every entry between and including the first and the last is selected

**Your Enviroment**
 - SMPlayer version: 21.8.0
 - OS: Kubuntu 21.04, KDE Plasma 5.22.4, QT 5.15.2
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [  ] MPlayer
 [X] MPV

I think the issue is the "single click to play" action in playlist window. Using smplayer 21.8.0 on Windows 10 the playlist uses double click to start playing entries and thus the issue does not occur there. So the solution might be to change the behaviour on linux to "double click to play", too.

I found http://old-forum.smplayer.info/viewtopic.php?f=2&t=343 but I was not able to find any UI/Style/etc combination that changes this behavior.

**Comment by smplayer-dev** [comment] 2021-08-29 07:15
I think this is caused by kde, it doesn't happen on gnome (or any other desktop). Maybe you can find an option in the kde settings to turn off a single click as a double click.

**Comment by sleeksorrow** [comment] 2021-08-29 07:42
Thank you for your quick response. KDE has a setting to choose single click or double click on files and folders (Settings > Workspace Behavior > General Behavior : in "Clicking files or folders" select: "Select them"). And while the smplayer playlist imo is not really a file or folder selection, this setting actually changes this behavior. I count that as a workaround.

But actually I prefer single click in all other QT applications like dolphin file manager. All the QT applications I use everyday work fine with single click behavior. smplayer is my only application that has issues with that. So I'd like to refrain from changing my whole DE behavior just to overcome one bug in one application.

So in case it's not feasible to fix smplayer to work with single click action, maybe there is a way to set double click action only for a single QT application? Maybe there is a QT environment variable that I can set before starting smplayer? And if yes, maybe it's worth hardcoding this into smplayer if single click is not working anyway?

**Comment by smplayer-dev** [comment] 2021-08-30 13:51
I think this is fixed in version 9900, could you test it?
There's a package for ubuntu 21.04 here: 
https://github.com/smplayer-dev/smplayer/actions/runs/1181886984

**Comment by sleeksorrow** [comment] 2021-08-30 15:16
This works perfectly for me, the playlist constantly uses double click action for play and allows all single click actions for selecting.
Awesome, thank you so much for your work!

**Closed as completed** 2021-08-30 15:27 UTC
Labels: bug, fixed

**Comment by LandisTwo** [comment] 2022-10-27 20:04
How do I re-enable it on my 5 systems (only one is currently updated to a version that is affected, but eventually all will)?
'selecting multiple songs in a play list' is a 'once in a while' if ever thing (editing a .m3u in SublimeText is quicker, easier anyways), Selecting (clicking on) a song to play is a 'many times a day thing' especially when Everything else I do, all day is single click. 'double-click' becomes: stop, come back, double-click, continue on. so basically quadruple-click and brake in flow, yuck.
Thanks, Landis.
