### ISSUE TITLE
wayland energy saving enabled during video play

### ISSUE THREAD

**Issue by miku84** [smplayer-dev/smplayer#7] opened 2021-03-16 20:10 UTC
Hi,

On wayland Plasma 5 manjaro i found when I am watching a movie with smplayer then after 3 minute monitor goes off as per energy saving settings (smplayer settings default, even disable screensaver). I think video play should not allow energy saving.

Thanks

**Comment by smplayer-dev** [comment] 2021-03-17 09:04
SMPlayer just passes mpv or mplayer an option to stop the screensaver. If it doesn't work correctly then it's a bug in either mpv/mplayer or somewhere else (desktop?). So I think I can't fix this issue.

**Comment by miku84** [comment] 2021-03-17 19:49
I see, but MPV itself does not do this issue when using it alone, also any other players does not do it, so it cannot be desktop issue. It happens only with smplayer. 

I think this is not screensaver, but energy saving. When using mpv alone it prohibits energy saving, when using mpv with smplayer in wayland, then it does not do it. So I think it would be worth to check it.

**Comment by smplayer-dev** [comment] 2021-03-23 13:00
I was able to reproduce the problem in Ubuntu 20.04. However the problem happens too when playing something with mpv alone.

**Comment by smplayer-dev** [comment] 2021-03-23 13:17
A workaround for gnome would be running smplayer this way:
`gnome-session-inhibit smplayer`

**Comment by miku84** [comment] 2021-03-23 13:29
Hi,
Thanks for checking. So you are saying that mpv has the issue as well? Strange, it was working for me (with wayland config for mpv).

With further testing I noticed that this issue only happens when I use the workaround: QT_QPA_PLATFORM=xcb smplayer and not native wayland smplayer. 

But this is what I could not manage to work:
https://github.com/smplayer-dev/smplayer/issues/6

So if that issue is solved, then there is no need for workaround so this issue could be closed as well :)

**Comment by smplayer-dev** [comment] 2021-03-23 13:40
> Hi,
> Thanks for checking. So you are saying that mpv has the issue as well? Strange, it was working for me (with wayland config for mpv).

What version of mpv are you using?
It's strange anyway because if mpv can turn off energy saving then it should do it as well when run by smplayer.

> With further testing I noticed that this issue only happens when I use the workaround: QT_QPA_PLATFORM=xcb smplayer and not native wayland smplayer.
> 
> But this is what I could not manage to work:
> #6
> 
> So if that issue is solved, then there is no need for workaround so this issue could be closed as well :)

Unfortunately that issue is not easy to fix.

**Comment by miku84** [comment] 2021-03-23 13:48
https://archlinux.org/packages/community/x86_64/mpv/
mpv 1:0.33.0-4

with --gpu-context=wayland

**Comment by smplayer-dev** [comment] 2021-03-24 16:15
I think this is fixed in https://github.com/smplayer-dev/smplayer/commit/d83ad1f1b86987e7ed75780037f63185a307ddb2 but I can only test on gnome.

**Closed as completed by smplayer-dev** 2021-03-24 16:15 UTC
Labels: bug, fixed
